// Analog Food — Database Seed Script
// Run AFTER schema.sql has been executed in Supabase SQL Editor
// Usage: node scripts/seed-db.mjs

import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { resolve } from 'path'

// Load from .env.local
const envPath = resolve(process.cwd(), '.env.local')
const env = Object.fromEntries(
  readFileSync(envPath, 'utf8')
    .split('\n')
    .filter(l => l.includes('='))
    .map(l => l.split('=').map(p => p.trim()))
)

const SUPABASE_URL = env['NEXT_PUBLIC_SUPABASE_URL']
const SERVICE_ROLE_KEY = env['SUPABASE_SERVICE_ROLE_KEY']

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY)

const vendors = [
  { name: 'Brooklyn Grange Rooftop Farm', type: 'farm', lat: 40.7282, lng: -73.9442, address: '37-18 Northern Blvd', city: 'Long Island City', state: 'NY', zip: '11101', website: 'https://brooklyngrangefarm.com', phone: '718-708-5986', hours: 'Seasonal farm stand — check website for hours', tags: ['organic','rooftop','CSA available','NYC'], highlights: ["Nation's largest rooftop soil farm",'Certified organic','CSA shares available','Community events'], verified: true },
  { name: 'Grand Army Plaza Greenmarket', type: 'farmers-market', lat: 40.6739, lng: -73.9700, address: 'Grand Army Plaza', city: 'Brooklyn', state: 'NY', zip: '11238', website: 'https://www.grownyc.org/greenmarket/brooklyn-grand-army-plaza', hours: 'Saturdays 8am–4pm, year-round', tags: ['GrowNYC','year-round','organic vendors','Brooklyn'], highlights: ['Year-round Saturday market','Multiple certified organic farms','Seasonal local produce','Artisan food producers'], verified: true },
  { name: 'Re_ Grocery', type: 'specialty-grocer', lat: 40.6782, lng: -73.9442, address: '175 Third Ave', city: 'Brooklyn', state: 'NY', zip: '11217', website: 'https://re-grocery.com', hours: 'Mon–Sat 9am–9pm, Sun 10am–7pm', tags: ['zero waste','organic','local','specialty'], highlights: ['Zero-waste focus','Certified organic products','Locally sourced where possible','Plastic-free bulk section'], verified: true },
  { name: 'Farm to People', type: 'specialty-grocer', lat: 40.7128, lng: -74.0060, address: 'Online + NYC Delivery', city: 'New York', state: 'NY', zip: '10001', website: 'https://farmtopeople.com', hours: 'Online store, local delivery', tags: ['delivery','CSA-style','organic','direct from farms'], highlights: ['Direct farmer relationships','Weekly curated boxes','Certified organic options','Transparent sourcing'], verified: true },
  { name: 'Windfall Farms at Union Square Greenmarket', type: 'farmers-market', lat: 40.7359, lng: -73.9906, address: 'Union Square Park (Vendor)', city: 'New York', state: 'NY', zip: '10003', website: 'https://www.grownyc.org/greenmarket/manhattan-union-square-m', hours: 'Mon, Wed, Fri, Sat 8am–6pm', tags: ['GrowNYC','certified organic','vegetables','herbs'], highlights: ['Certified organic vegetables','Rare heirloom varieties','Year-round presence at Union Square','Hudson Valley grown'], verified: true },
  { name: 'Stoneledge Farm CSA', type: 'csa', lat: 41.9848, lng: -74.5285, address: '5349 County Route 22', city: 'South Cairo', state: 'NY', zip: '12482', website: 'https://stoneledgefarm.com', hours: 'CSA pickup points throughout NYC', tags: ['CSA','certified organic','Hudson Valley','year-round'], highlights: ['Certified organic for 30+ years','Year-round CSA shares','Multiple NYC pickup locations','Community-focused'], verified: true },
  { name: 'Prospect Park Farmers Market', type: 'farmers-market', lat: 40.6601, lng: -73.9683, address: 'Prospect Park W & 15th St', city: 'Brooklyn', state: 'NY', zip: '11215', website: 'https://www.grownyc.org', hours: 'Saturdays 8am–1pm (seasonal, May–Nov)', tags: ['Brooklyn','seasonal','local farms','GrowNYC'], highlights: ['Local Brooklyn vendors','Seasonal produce','Artisan food products','Pet-friendly market'], verified: true },
  { name: 'Greenhouse Holistic', type: 'specialty-grocer', lat: 40.7282, lng: -73.9537, address: '23 Meadow St', city: 'Brooklyn', state: 'NY', zip: '11206', website: 'https://www.greenholisticnyc.com', hours: 'Mon–Sat 10am–8pm, Sun 11am–6pm', tags: ['holistic','organic','supplements','local'], highlights: ['Certified organic grocery','Natural supplements and remedies','Local NYC producers','Knowledgeable staff'], verified: true },
  { name: 'Queens County Farm Museum', type: 'farm', lat: 40.7416, lng: -73.7425, address: '73-50 Little Neck Pkwy', city: 'Floral Park', state: 'NY', zip: '11004', website: 'https://queensfarm.org', hours: 'Farm stand Sat–Sun 10am–4pm (seasonal)', tags: ['historic','educational','organic','farm stand'], highlights: ["NYC's largest working farm",'Historic farm since 1697','Seasonal farm stand','Educational programming'], verified: true },
  { name: 'Fort Greene Park Farmers Market', type: 'farmers-market', lat: 40.6908, lng: -73.9742, address: 'Washington Park (in Fort Greene Park)', city: 'Brooklyn', state: 'NY', zip: '11205', website: 'https://www.grownyc.org/greenmarket/brooklyn-fort-greene', hours: 'Saturdays 8am–3pm, year-round', tags: ['Brooklyn','year-round','GrowNYC','organic'], highlights: ['Year-round Saturday market','Certified organic vendors','Baked goods and artisan products','Community gathering space'], verified: true },
  { name: 'GrowNYC — Union Square Greenmarket', type: 'farmers-market', lat: 40.7361, lng: -73.9906, address: 'Union Square Park (N side)', city: 'New York', state: 'NY', zip: '10003', website: 'https://www.grownyc.org/greenmarket/manhattan-union-square-m', hours: 'Mon, Wed, Fri, Sat 8am–6pm, year-round', tags: ['GrowNYC','flagship market','year-round','organic'], highlights: ["NYC's flagship greenmarket",'140+ vendors at peak season','Multiple certified organic farms','Year-round operation'], verified: true },
  { name: 'Carroll Gardens Greenmarket', type: 'farmers-market', lat: 40.6784, lng: -74.0001, address: 'Carroll Park (Smith St at Carroll)', city: 'Brooklyn', state: 'NY', zip: '11231', website: 'https://www.grownyc.org', hours: 'Sundays 8am–3pm (seasonal, May–Nov)', tags: ['Brooklyn','seasonal','organic','community'], highlights: ['Neighborhood farmers market','Seasonal local produce','Eggs and dairy from certified farms','Family-friendly'], verified: true },
  { name: 'Integral Yoga Natural Foods', type: 'specialty-grocer', lat: 40.7330, lng: -74.0065, address: '229 W 13th St', city: 'New York', state: 'NY', zip: '10011', website: 'https://integralyoganaturalfoods.com', hours: 'Mon–Fri 9am–9pm, Sat–Sun 9am–8:30pm', tags: ['organic','vegetarian','supplements','West Village'], highlights: ['Organic grocery and bulk foods','Extensive vegan and vegetarian selection','Clean supplements','West Village staple since 1972'], verified: true },
  { name: 'Park Slope Food Coop', type: 'specialty-grocer', lat: 40.6653, lng: -73.9793, address: '782 Union St', city: 'Brooklyn', state: 'NY', zip: '11215', website: 'https://foodcoop.com', phone: '718-622-0560', hours: 'Daily 8am–10pm (members)', tags: ['cooperative','organic','local','bulk foods'], highlights: ['Member-owned food cooperative','Extensive organic selection','Below-market prices for members','Strong local sourcing commitment'], verified: true },
  { name: 'Manhattan Fruit Exchange', type: 'specialty-grocer', lat: 40.7424, lng: -74.0048, address: '399 W 12th St (Chelsea Market)', city: 'New York', state: 'NY', zip: '10014', website: 'https://www.chelseamarket.com', hours: 'Mon–Sat 7am–8pm, Sun 8am–7pm', tags: ['Chelsea Market','organic','local','fresh produce'], highlights: ['Inside Chelsea Market','Exceptional organic produce selection','Local and imported varieties','Seasonal specials'], verified: true },
  { name: 'Bodhitree Farm CSA', type: 'csa', lat: 41.3548, lng: -74.3882, address: 'Orange County Farm', city: 'Warwick', state: 'NY', zip: '10990', website: 'https://bodhitreefarm.com', hours: 'Weekly pickup at NYC drop points', tags: ['CSA','biodynamic','organic','Hudson Valley'], highlights: ['Biodynamic and certified organic','Seasonal vegetable shares','NYC pickup locations','Small-scale family farm'], verified: true },
  { name: 'Madura Farm at Inwood Greenmarket', type: 'farmers-market', lat: 40.8665, lng: -73.9212, address: 'Isham Park, Inwood', city: 'New York', state: 'NY', zip: '10034', website: 'https://www.grownyc.org', hours: 'Saturdays 8am–3pm (seasonal)', tags: ['Inwood','seasonal','certified organic','uptown'], highlights: ['Northern Manhattan market','Certified organic vegetables','Fresh eggs and dairy','Underserved community access'], verified: true },
  { name: 'Smorgasburg Prospect Park', type: 'farmers-market', lat: 40.6627, lng: -73.9692, address: 'Prospect Park Bandshell', city: 'Brooklyn', state: 'NY', zip: '11215', website: 'https://www.smorgasburg.com', hours: 'Sundays 11am–6pm (April–October)', tags: ['artisan food','organic vendors','Brooklyn','outdoor market'], highlights: ['Curated artisan food vendors','Many organic and clean-ingredient options','Brooklyn outdoor food market','Seasonal April–October'], verified: false },
  { name: 'Transmitter Park Greenmarket', type: 'farmers-market', lat: 40.7274, lng: -73.9581, address: 'Transmitter Park, Greenpoint Ave', city: 'Brooklyn', state: 'NY', zip: '11222', website: 'https://www.grownyc.org', hours: 'Saturdays 8am–3pm (seasonal)', tags: ['Greenpoint','seasonal','organic','Brooklyn'], highlights: ['Waterfront market in Greenpoint','Certified organic produce','Local honey and preserves','Scenic East River location'], verified: true },
  { name: 'The Berry Farm at Hallockville', type: 'farm', lat: 40.9530, lng: -72.5418, address: '6038 Sound Ave', city: 'Riverhead', state: 'NY', zip: '11901', website: 'https://hallockville.org', hours: 'Farm stand Sat–Sun 10am–4pm (seasonal)', tags: ['Long Island','organic','berries','u-pick'], highlights: ['Certified organic berry farm','U-pick strawberries and blueberries','Historic North Fork farm','CSA shares available'], verified: true },
  { name: 'Northshire Farm CSA', type: 'csa', lat: 41.8027, lng: -73.8718, address: 'Columbia County', city: 'Hudson', state: 'NY', zip: '12534', hours: 'Weekly pickup at multiple NYC locations', tags: ['CSA','certified organic','Columbia County','vegetables'], highlights: ['Certified organic since 2001','Seasonal vegetable and fruit shares','Brooklyn and Manhattan pickup points','Transparent farming practices'], verified: false },
  { name: 'Gorilla Coffee & Provisions', type: 'specialty-grocer', lat: 40.6826, lng: -73.9793, address: '97 Fifth Ave', city: 'Brooklyn', state: 'NY', zip: '11217', website: 'https://gorillacoffee.com', hours: 'Daily 7am–7pm', tags: ['coffee','organic','local','specialty'], highlights: ['Direct-trade organic coffee','Local organic grocery selection','Clean ingredient snacks','Brooklyn institution'], verified: false },
  { name: 'Eataly NYC Flatiron', type: 'specialty-grocer', lat: 40.7424, lng: -73.9893, address: '200 Fifth Ave', city: 'New York', state: 'NY', zip: '10010', website: 'https://www.eataly.com/us_en/stores/nyc-flatiron/', hours: 'Daily 9am–11pm', tags: ['Italian','imported','quality ingredients','specialty'], highlights: ['Import quality Italian products','Fresh pasta and bread','Specialty organic selections','Artisan producers'], verified: false },
]

const ingredients = [
  { name: 'Red 40 (Allura Red)', aliases: ['Red 40','Allura Red AC','FD&C Red No. 40','E129'], danger_level: 'high', description: 'A petroleum-derived synthetic dye used to color foods red or orange. Linked to hyperactivity in children, allergic reactions, and possible carcinogenic effects. The EU requires warning labels on foods containing it.', banned_in: ['European Union (warning label required)','Norway','Finland','France (partial ban)'], clean_alternative: 'Beet juice powder, pomegranate juice concentrate, or hibiscus extract for natural red color', personal_note: "Analog Food's founder has experienced this firsthand — his son becomes violently ill hours after consuming Red 40." },
  { name: 'BHA (Butylated Hydroxyanisole)', aliases: ['BHA','E320','tert-Butyl-4-hydroxyanisole'], danger_level: 'high', description: 'A synthetic antioxidant preservative used in cereals, butter, snack foods, and beer. Listed as a possible human carcinogen by the National Toxicology Program. Disrupts hormone function.', banned_in: ['Japan','United Kingdom','European Union (restricted)','Australia (restricted)'], clean_alternative: 'Rosemary extract, vitamin E (tocopherols), or ascorbic acid as natural preservatives' },
  { name: 'BHT (Butylated Hydroxytoluene)', aliases: ['BHT','E321','dibutylhydroxytoluene'], danger_level: 'medium', description: 'A synthetic preservative chemically similar to BHA. Found in cereals, chips, and cosmetics. Some studies suggest carcinogenic properties. Precautionary bans in several countries.', banned_in: ['United Kingdom','Japan','Romania','Sweden','Australia (restricted)'], clean_alternative: 'Vitamin E (tocopherols), rosemary extract, or smaller batch production without synthetic preservation' },
  { name: 'Potassium Bromate', aliases: ['Potassium Bromate','E924','bromated flour'], danger_level: 'high', description: 'Added to bread flour to strengthen dough and improve rise. Classified as a possible carcinogen by the IARC. Residual bromate remains in finished baked goods. Banned in most countries since the 1990s.', banned_in: ['European Union','United Kingdom','Canada','China','Brazil','Nigeria','Sri Lanka'], clean_alternative: 'Ascorbic acid (vitamin C), malted barley flour, or simply unbromated unbleached flour' },
  { name: 'rBGH / rBST', aliases: ['rBGH','rBST','recombinant bovine growth hormone','Posilac'], danger_level: 'high', description: 'Synthetic growth hormone injected into dairy cows to increase milk production. Increases IGF-1 levels in milk, which has been linked to breast, colon, and prostate cancers.', banned_in: ['European Union','Canada','Australia','New Zealand','Japan','Israel'], clean_alternative: 'Certified organic dairy products or products labeled "rBGH-free" or "rBST-free"' },
  { name: 'Atrazine', aliases: ['Atrazine','2-chloro-4-ethylamino-6-isopropylamino-s-triazine'], danger_level: 'high', description: 'One of the most widely used herbicides in the US, applied to corn, sugarcane, and sorghum. A powerful endocrine disruptor linked to reproductive harm. Contaminates drinking water. Banned in the EU since 2004.', banned_in: ['European Union','Switzerland','Germany','Austria','Italy','Sweden','36+ countries total'], clean_alternative: 'Choose certified organic produce, especially corn. Support farms using cover crops and integrated pest management.' },
  { name: 'Chlorpyrifos', aliases: ['Chlorpyrifos','Dursban','Lorsban','CPF'], danger_level: 'high', description: 'An organophosphate pesticide used on fruits, vegetables, and nuts. Linked to neurodevelopmental harm in children, including lower IQ and developmental delays.', banned_in: ['European Union','United Kingdom','Canada','Australia','New Zealand','China'], clean_alternative: 'Buy certified organic produce, especially apples, citrus, and grapes. Wash all produce thoroughly.' },
  { name: 'High Fructose Corn Syrup', aliases: ['HFCS','corn syrup','glucose-fructose syrup','isoglucose'], danger_level: 'medium', description: 'A highly processed sweetener derived from corn starch. Metabolized differently than regular sugar, contributing to fatty liver disease, obesity, insulin resistance, and metabolic syndrome.', banned_in: ['European Union (restricted/replaced)','Hungary','France (sugar tax targeting it)'], clean_alternative: 'Raw honey, pure maple syrup, or date syrup. Look for products sweetened with organic cane sugar.' },
  { name: 'Aspartame', aliases: ['Aspartame','NutraSweet','Equal','E951'], danger_level: 'medium', description: 'An artificial sweetener used in diet sodas and "sugar-free" products. The WHO classified it as "possibly carcinogenic" in 2023. Breaks down into methanol and aspartic acid in the body.', banned_in: ['Not fully banned, but restricted in some EU contexts','Under review by WHO'], clean_alternative: 'Stevia leaf extract (organic), monk fruit sweetener, or simply reducing overall sweetener use' },
  { name: 'Titanium Dioxide', aliases: ['Titanium Dioxide','TiO2','E171','CI 77891'], danger_level: 'medium', description: 'A white pigment used to make foods like candy, chewing gum, and frosting appear bright white. The EU banned it in 2022 after EFSA concluded it could cause DNA damage.', banned_in: ['European Union (banned 2022)','United Kingdom (under review)','France (banned 2020)'], clean_alternative: 'Natural white colorings from calcium carbonate, starch, or simply no artificial whitening agent' },
  { name: 'Brominated Vegetable Oil', aliases: ['BVO','Brominated Vegetable Oil','E443'], danger_level: 'high', description: 'Used to keep citrus flavoring suspended in sodas. Bromine accumulates in body fat and breast milk. Linked to memory loss, nerve damage, and skin lesions at high doses. The FDA revoked its authorization in 2024.', banned_in: ['European Union','India','Japan','United Kingdom','Canada'], clean_alternative: 'Choose beverages without artificial emulsifiers. Natural citrus oils do not require BVO as a carrier.' },
  { name: 'Propyl Paraben', aliases: ['Propyl Paraben','E216','propylhydroxybenzoate'], danger_level: 'medium', description: 'A preservative used in baked goods, tortillas, and food dyes. Acts as a xenoestrogen (mimics estrogen), linked to reproductive harm, reduced sperm count, and early puberty. The EU banned it in foods in 2006.', banned_in: ['European Union','Denmark','Japan'], clean_alternative: 'Naturally preserved foods using vitamin E, rosemary extract, or lacto-fermentation' },
  { name: 'Azodicarbonamide', aliases: ['ADA','Azodicarbonamide','E927a','flour bleaching agent'], danger_level: 'medium', description: 'A flour bleaching and dough conditioning agent used in breads and fast food buns. Also used to make yoga mats and shoe soles. Breaks down into semicarbazide during baking, a potential carcinogen.', banned_in: ['European Union','United Kingdom','Australia','Singapore (fined if used)'], clean_alternative: 'Bread made with unbromated, unbleached flour. European-style bread production uses neither ADA nor potassium bromate.' },
  { name: 'Yellow 5 (Tartrazine)', aliases: ['Yellow 5','Tartrazine','FD&C Yellow No. 5','E102'], danger_level: 'medium', description: 'A synthetic lemon-yellow dye derived from coal tar. Linked to hyperactivity in children, hives, and asthma. The EU requires a warning label citing effects on activity and attention in children.', banned_in: ['Norway','Austria','EU (warning label required)','Finland'], clean_alternative: 'Turmeric, saffron, or beta-carotene for natural yellow coloring' },
  { name: 'Yellow 6 (Sunset Yellow)', aliases: ['Yellow 6','Sunset Yellow','FD&C Yellow No. 6','E110'], danger_level: 'medium', description: 'A coal tar-derived orange-yellow dye used in beverages, candy, and baked goods. EU-required warning label cites attention and hyperactivity effects in children.', banned_in: ['Norway','Finland','EU (warning label required)'], clean_alternative: 'Annatto, paprika extract, or beta-carotene for natural orange-yellow hues' },
  { name: 'Sodium Nitrate / Nitrite', aliases: ['Sodium Nitrate','Sodium Nitrite','E249','E250','E251','E252'], danger_level: 'high', description: 'Preservatives and color fixers used in processed meats. Form nitrosamines in the body, which are potent carcinogens. Linked to colorectal cancer, Type 1 diabetes, and Alzheimer\'s disease.', banned_in: ['EU (restricted, phased out in organic meats)','UK (phased out plan)','France (partial ban on cured meats)'], clean_alternative: 'Uncured meats preserved with celery juice or sea salt. Look for "no added nitrates/nitrites" labels.' },
  { name: 'Glyphosate', aliases: ['Glyphosate','Roundup','N-(phosphonomethyl)glycine'], danger_level: 'high', description: 'The world\'s most widely used herbicide. The WHO classified it as "probably carcinogenic." Found in urine samples of 80%+ of Americans. Linked to non-Hodgkin lymphoma.', banned_in: ['Austria','Vietnam','Sri Lanka','Thailand (partial)','Mexico (phase-out)','14+ countries total'], clean_alternative: 'Certified organic oats, wheat, and legumes. Glyphosate cannot be used on certified organic crops.' },
  { name: 'Olestra (Olean)', aliases: ['Olestra','Olean','sucrose polyester'], danger_level: 'medium', description: 'A fat substitute that passes through the body undigested. Causes gastrointestinal distress and depletes fat-soluble vitamins (A, D, E, K). Still used in some fat-free snack chips in the US.', banned_in: ['European Union','United Kingdom','Canada'], clean_alternative: 'Whole food snacks with naturally occurring healthy fats. Air-popped popcorn with olive oil.' },
  { name: 'Saccharin', aliases: ['Saccharin',"Sweet'N Low",'E954','sodium saccharin'], danger_level: 'low', description: 'The oldest artificial sweetener. Previously carried a warning label for bladder cancer risk. Recent studies link it to disruption of gut microbiome and may impair glucose tolerance.', banned_in: ['Canada (was banned 1977–2014)','Previously restricted in EU'], clean_alternative: 'Stevia, monk fruit, or erythritol for zero-calorie sweetening without synthetic chemistry' },
  { name: 'Carmine (Red 4)', aliases: ['Carmine','Red 4','cochineal extract','E120','crimson lake'], danger_level: 'low', description: 'A red dye made from crushed cochineal insects. Causes severe allergic reactions including anaphylaxis in some people. The FDA requires it to be labeled by name.', banned_in: ['Not banned, but requires mandatory labeling in EU and US'], clean_alternative: 'Beet juice powder, raspberry extract, or hibiscus concentrate for natural red' },
]

async function seed() {
  console.log('🌱 Seeding Analog Food database...\n')

  // Seed vendors
  console.log(`Inserting ${vendors.length} vendors...`)
  const { error: vendorError } = await supabase
    .from('vendors')
    .insert(vendors)

  if (vendorError) {
    console.error('❌ Vendor insert failed:', vendorError.message)
    console.error('   Make sure you have run supabase/schema.sql first.')
    process.exit(1)
  }
  console.log(`✅ ${vendors.length} vendors inserted`)

  // Seed ingredients
  console.log(`Inserting ${ingredients.length} ingredients...`)
  const { error: ingredientError } = await supabase
    .from('ingredients')
    .insert(ingredients)

  if (ingredientError) {
    console.error('❌ Ingredient insert failed:', ingredientError.message)
    process.exit(1)
  }
  console.log(`✅ ${ingredients.length} ingredients inserted`)

  console.log('\n✅ Seed complete. Your Analog Food database is ready.')
}

seed()
